
POST http://localhost:4400/employee
Content-Type: application/json

{
    "first_name":"May",
    "last_name":"Dean",
    "email":"name@mailesd.com",
    "cohort":7   
}


###

GET  http://localhost:4400/employee
Content-Type: application/json